version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deceptive-domains-checker
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - KEITARO_API_URL=${KEITARO_API_URL}
      - KEITARO_API_KEY=${KEITARO_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - CHECK_INTERVAL_MINUTES=${CHECK_INTERVAL_MINUTES:-30}
      - BROWSER_TIMEOUT_MS=${BROWSER_TIMEOUT_MS:-30000}
      - MAX_CONCURRENT_CHECKS=${MAX_CONCURRENT_CHECKS:-10}
      - REQUEST_TIMEOUT_MS=${REQUEST_TIMEOUT_MS:-15000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G

networks:
  app-network:
    driver: bridge

volumes:
  logs:
    driver: local
